### ISSUE TITLE
support for a 'jump-to' feature in last flow action

### ISSUE THREAD

**Issue by gundakiransatsyil** [aleksandr-m/struts2-actionflow#2]
Hi, Thank you for the plugin. It works as expected (Previous and Next flows).

a) There are several Tabs, user lands in the 'first tab' and user fills the data and clicks 'next'.. If there are validation errors, user is taken back to current tab (input) else takes 'next' tab in the flow. This is an existing feature supported by your plugin. Works as expected.

b) However, I have a requirement that user 'can click on any tab'. when user clicks on any 'tab', following things need to happen
     > current 'tab' needs to be 'submitted' (so if there are any 'validation' errors, user is taken back to current tab
    > if there are no 'validation' errors then user would be taken to the 'clicked tab'.

In order to achieve this, I introduced a request parameter called 'JumpToAction'. This will hold the 'actionName' (in the action flow) that needs to jump to. when the user clicks on the tab, I am populating the JumpToAction of target tab and calling 'nextAction'. In the 'Next action' I overrode the 'nextActionFlowAction' method and return the action name that is carried in 'JumpToAction'. This way it is going to the 'required tab' not the 'adjacent one'.

This works fine, however this fails if user is in the 'last but one' tab and clicks some other 'tab'. The reason is that ActionFlowInterceptor determines 'lastFlowAction' and sees it as 'last step' and takes you to the 'last action'. It is not waiting and looking at the real target action (as  nextActionFlowAction  would have returned some action that is not last).

Is there any way you can accommodate 'Jump to' behavior in your current plugin? 

Perhaps, if 'JumpToAction' request parameter has 'some value' then don't evaluate 'lastFlowAction'.. It is a crude fix. but you might fix it more elegantly.

Thank you, Kiran

**Comment by aleksandr-m** [comment]
@gundakiransatsyil ping...
