### ISSUE TITLE
Object Scope lost through steps

### ISSUE THREAD

**Issue by pablocossioabastoflor** [aleksandr-m/struts2-actionflow#3]
Hi thanks a lot for your Plugin,

I'm new implementing it, and I face a problem. I marked some Action properties to keep in the scope with the annotation "@ActionFlowScope". In the first step I fill out these fields and after submit "/next" these properties are setted with new values. Then when I submit the second step, the properties of the first step are NULL. What do I missing?

This is the source:

    @ActionFlowScope
    public class RestaurantWizardAction extends BaseAction {

    protected final RestaurantMgmtService restaurantMgmtService = RestaurantMgmtService.INSTANCE;
    protected final CuisineService cuisineService = CuisineService.INSTANCE;

     @ActionFlowScope
    private RestaurantProfile restaurantProfile;
    @ActionFlowScope
    private List<Integer> enterpriseTypeIDs;
    @ActionFlowScope
    private List<Integer> cuisineTypeIds;

    public RestaurantProfile getRestaurantProfile() {
        return restaurantProfile;
    }

    public void setRestaurantProfile(RestaurantProfile restaurantProfile) {
        this.restaurantProfile = restaurantProfile;
    }

    public List<Integer> getEnterpriseTypeIDs() {
        return enterpriseTypeIDs;
    }

    public void setEnterpriseTypeIDs(List<Integer> enterpriseTypeIDs) {
        this.enterpriseTypeIDs = enterpriseTypeIDs;
    }

    public List<Integer> getCuisineTypeIds() {
        return cuisineTypeIds;
    }

    public void setCuisineTypeIds(List<Integer> cuisineTypeIds) {
        this.cuisineTypeIds = cuisineTypeIds;
    }

     public String start() {
        
        return SUCCESS;
    }

    public String step1() {
        //The form is sent and objects are populated
        System.out.println("\nsubmited step 1");
        System.out.println(restaurantProfile);
        System.out.println(getCuisineTypeIds());
        System.out.println(getEnterpriseTypeIDs());
        return SUCCESS;
    }

    public String step2() {
       //the objects of step 1 are NULL
        System.out.println("\nsubmited step 2");
        System.out.println(restaurantProfile);
        System.out.println(getCuisineTypeIds());
        System.out.println(getEnterpriseTypeIDs());
        return SUCCESS;
    }
    }

**Comment by aleksandr-m** [comment]
Hey.
You aren't missing anything. Currently values from the action flow scope will be set back to the action only on `view` actions. You can easily verify that by putting `<s:property value="cuisineTypeIds"/>` tag in your next steps JSP-s or by going back into the first step.

Can you explain what is the use case for which you need those values in the next steps action methods?

**Comment by pablocossioabastoflor** [comment]
Thanks for reply,

I just was testing if the objects were available, but I misunderstood it.
What I need to do is, build a wizard populating objects, and in the last step I need to persists all the objects to the database. So how could I get all the objects on the last step Action method? maybe through the session?

**Comment by aleksandr-m** [comment]
You can create hidden fields in the last step with all the data from the previous steps and because of `@ActionFlowScope` the values will be there and will be submitted to your last step action.

But it's seems that it is pretty reasonably case that values from previous steps should be available in the next action methods. I need some time to think about it and to implement this feature request. Don't close this issue, I'll notify you if/when this feature will be implemented.

Thank you for the feedback.

**Comment by pablocossioabastoflor** [comment]
Thanks a lot to you. Regards

**Comment by aleksandr-m** [comment]
@pablocossioabastoflor 
Can you clone develop branch, install it with maven and use snapshot version of this plugin in your project to see if it works like you are expecting?

**Comment by pablocossioabastoflor** [comment]
Ok I will do it in a few days please. I'll let you know the results. Thanks a lot.

**Comment by aleksandr-m** [comment]
Version `2.4.0` is released.

**Comment by aleksandr-m** [comment]
@pablocossioabastoflor Thank you for the feedback.

**Comment by pablocossioabastoflor** [comment]
I was finally able to try it!! and working perfect. Thanks a lot.
