### ISSUE TITLE
Possible design issues

### ISSUE THREAD

**Issue by gundakiransatsyil** [aleksandr-m/struts2-actionflow#4]
Struts2 interceptors should be designed as 'stateless' (state that cannot be shared between any two requests) . In ActionFlowInterceptor, it is using following fields as a 'STATE' and this state is being used in "addPreResultListener.addPreResultListener" as well. when 2 concurrent requests come, actionName/indexCurrent would be changed and it would lead to a corrupted flow. Not only these 2 attributes there are few more attributes it is using as a 'state' that was shared. 

<code>
    /** Current action name retrieved from invocation context. */
    private String actionName;
    /** Index of the current action from the flowMap. */
    private int indexCurrent;
</code>

**Comment by aleksandr-m** [comment]
The `actionName` is retrieved each time from the action context and `indexCurrent` is based on `actionName`. So the *state* **ISN'T** shared.

Do you have specific problem with the plugin?
If yes. Can you create a minimal failing example project?

**Comment by gundakiransatsyil** [comment]
Think about it, if 2 threads concurrently coming to the request. one thread comes to the line 184 and derives actionName as 'action-a' and continuing the execution and waiting for the result listener (beforeResult) to execute and second thread comes to the line 184 and changes the actionName to 'action-b' and 1st thread is now continuing with 'beforeResult' and it sees the actionName as 'action-b' because it changed the 'STATE'.I am not telling this hypothetically, I ran into this issue when I am testing the plugin in multi-user environment and after reviewing the code, I wasn't surprised.Kiran


-------- Original Message --------
Subject: Re: [struts2-actionflow] Possible design issues (#4)

**Comment by aleksandr-m** [comment]
Well, there is some chance that this will actually happen. I'll see what I can do about it. Next time consider writing some test case so your statements won't be hypothetical.

**Comment by gundakiransatsyil** [comment]
I will try put the test-cases to replicate the issue. I will let you know.

For now, I had to put a temporary patch to move the 'state' to session. If you like, I can submit that patch. 

Please don't think that I am critical of your code. It is an excellent idea and I liked the approach. It just needs to be tighten to be used for production applications.

Thanks

**Comment by aleksandr-m** [comment]
Of course. You can create a Pull Request to submit your changes.

**Comment by aleksandr-m** [comment]
Version `2.4.0` is released.

**Comment by aleksandr-m** [comment]
@gundakiransatsyil Thanks for reporting.
