### ISSUE TITLE
It's mandatory to have each Flow on a separated Struts Package?

### ISSUE THREAD

**Issue by pablocossioabastoflor** [aleksandr-m/struts2-actionflow#5]
I used the flow in a separated Struts Package and it worked for me before.

package name="restaurant-wizard" extends="actionflow-default" namespace="/admin/restaurantWizard">

--Action mapings--

/package

Now, I'm trying to implement it in the main package where I have another action mappings, and it's not working. So my question is. Is it mandatory to have flows on separated Struts Packages? 

Thanks in advance.

**Comment by aleksandr-m** [comment]
You can use other action mappings (outside of flow scope) in same package. How it isn't working for you? Can you show your package configuration which doesn't work?

**Comment by pablocossioabastoflor** [comment]
Thanks, it worked for me.
